version: "3.8"

services:
  db:
    image: mysql:9.2
    container_name: golangproject-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: golangproject-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      DB_HOST: db
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_NAME: your_db_name
    command: ["/app/main"]

volumes:
  mysql_data:
